// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
)

const _ = grpc.SupportPackageIsVersion7

type TunnelClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Tunnel_StreamClient, error)
}

type tunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelClient(cc grpc.ClientConnInterface) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Tunnel_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tunnel_ServiceDesc.Streams[0], "/tunnelpb.Tunnel/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelStreamClient{stream}
	return x, nil
}

type Tunnel_StreamClient interface {
	Send(*Frame) error
	Recv() (*Frame, error)
	grpc.ClientStream
}

type tunnelStreamClient struct {
	grpc.ClientStream
}

func (x *tunnelStreamClient) Send(m *Frame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelStreamClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type TunnelServer interface {
	Stream(Tunnel_StreamServer) error
	mustEmbedUnimplementedTunnelServer()
}

type UnimplementedTunnelServer struct {
}

func (UnimplementedTunnelServer) Stream(Tunnel_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func (UnimplementedTunnelServer) mustEmbedUnimplementedTunnelServer() {}

type UnsafeTunnelServer interface {
	mustEmbedUnimplementedTunnelServer()
}

func RegisterTunnelServer(s grpc.ServiceRegistrar, srv TunnelServer) {
	s.RegisterService(&Tunnel_ServiceDesc, srv)
}

func _Tunnel_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).Stream(&tunnelStreamServer{stream})
}

type Tunnel_StreamServer interface {
	Send(*Frame) error
	Recv() (*Frame, error)
	grpc.ServerStream
}

type tunnelStreamServer struct {
	grpc.ServerStream
}

func (x *tunnelStreamServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelStreamServer) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var Tunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnelpb.Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Tunnel_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnel.proto",
}
